### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by oleh-yanichko** [oleh-yanichko/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by vilderly** [comment]
Bugs is an anthropomorphic gray and white rabbit or hare who is famous for his flippant, insouciant personality. He is also characterized by a Brooklyn accent, his portrayal as a trickster, his signature carrot, and his catch phrase "Eh...What's up, doc?".
Bugs usually tries to placate his antagonist and avoid conflict but, when an antagonist pushes him too far, Bugs may address the audience and invoke his catchphrase "Of course you realize this means war!" before he retaliates in a devastating manner.
