### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by oleh-yanichko** [oleh-yanichko/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by vilderly** [comment]
Bugs Bunny on IMDb
Bugs Bunny at Toonopedia
Warner Bros. Studios
Bugs Bunny at Loonipedia
