### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by oleh-yanichko** [oleh-yanichko/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by vilderly** [comment]
Bugs Bunny is characterized as being clever and capable of outsmarting almost anyone who antagonizes him, including Elmer Fudd, Yosemite Sam, Tasmanian Devil, Marvin the Martian, Wile E. Coyote, Gossamer, Witch Hazel, Rocky and Mugsy, The Crusher, Beaky Buzzard, Willoughby, Count Bloodcount, Daffy Duck and a host of others. The only one to consistently beat Bugs is Cecil Turtle, who defeats Bugs in three consecutive shorts based on the premise of the Aesop fable The Tortoise and the Hare. In a rare villain turn, Bugs turns to a life of crime in 1949's Rebel Rabbit, taking on the entire United States government by vandalizing monuments in an effort to prove he is worth more than the two-cent bounty on his head; while he succeeds in raising the bounty to $1,000,000, the full force of the military ends up capturing Bugs and sending him to Alcatraz.
